///////////////////////////////////////////////////////////
//  DataModel.Customer_Payment_Details.cs
//  Implementation of the Class Customer_Payment_Details
//  Generated by Enterprise Architect
//  Created on:      05-Oct-2019 12:48:11
//  Original author: ABHILASH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;


using Indus.Store.Services;
using System.ComponentModel.DataAnnotations.Schema;

namespace Indus.Store.Models {
	public partial class Customer_Payment_Detail {



		~Customer_Payment_Detail(){

		}

		public Customer_Payment_Detail(){

		}

		public  string credit_card_detail{
			get;
			set;
		}

		public  int customer_id{
			get;
			set;
		}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public  int customer_payment_id{
			get;
			set;
		}

		public  int customer_payment_type_code{
			get;
			set;
		}
        public string payment_details
        {
            get;
            set;
        }

        //Navigation Properties
        public  Customer Customers{
			get;
			set;
		}

		public  Ref_Payment_Type Ref_Payment_Types{
			get;
			set;
		}

	}//end Customer_Payment_Details

}//end namespace Indus.Store.Services