///////////////////////////////////////////////////////////
//  DataModel.Order_Items.cs
//  Implementation of the Class Order_Items
//  Generated by Enterprise Architect
//  Created on:      05-Oct-2019 12:48:11
//  Original author: ABHILASH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;


using Indus.Store.Services;
using System.ComponentModel.DataAnnotations.Schema;

namespace Indus.Store.Models
{
	public partial class Order_Item {



		~Order_Item(){

		}

		public Order_Item(){

		}

		public  int order_id{
			get;
			set;
		}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public  int order_item_id{
			get;
			set;
		}

		public  int order_item_price{
			get;
			set;
		}

		public  int order_item_quantity{
			get;
			set;
		}

		public  int order_item_status_code{
			get;
			set;
		}



		public  String other_order_item_details{
			get;
			set;
		}

		public  int product_id{
			get;
			set;
		}


		public  String RMA_issued_by{
			get;
			set;
		}

		public  DateTime RMA_issued_date{
			get;
			set;
		}

		public  int RMA_number{
			get;
			set;
		}

        //Navigation Properties
        public Order Order
        {
            get;
            set;
        }
        public Ref_Order_Item_Status Ref_Order_Item_Status
        {
            get;
            set;
        }

    }//end Order_Items

}//end namespace Indus.Store.Services