///////////////////////////////////////////////////////////
//  DataModel.Orders.cs
//  Implementation of the Class Orders
//  Generated by Enterprise Architect
//  Created on:      05-Oct-2019 12:48:11
//  Original author: ABHILASH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;


using Indus.Store.Services;
using System.ComponentModel.DataAnnotations.Schema;

namespace Indus.Store.Models
{
	public partial class Order {



		~Order(){

		}

		public Order(){

		}

		public  int customer_id{
			get;
			set;
		}



		public  System.DateTime date_order_placed{
			get;
			set;
		}

		public  string order_details{
			get;
			set;
		}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public  int order_id{
			get;
			set;
		}

		public  int order_status_code{
			get;
			set;
		}

        //Navigation Properties
        public Customer Customer
        {
            get;
            set;
        }

        public  Ref_Order_Status Ref_Order_Status{
			get;
			set;
		}

        public ICollection<Order_Item> Order_Items
        { get; set; }

        public ICollection<Shipment> Shipments
        { get; set; }

    }//end Orders

}//end namespace Indus.Store.Services