///////////////////////////////////////////////////////////
//  DataModel.Payments.cs
//  Implementation of the Class Payments
//  Generated by Enterprise Architect
//  Created on:      05-Oct-2019 12:48:11
//  Original author: ABHILASH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;


using Indus.Store.Services;
using System.ComponentModel.DataAnnotations.Schema;

namespace Indus.Store.Models
{
	public partial class Payment {



		~Payment(){

		}

		public Payment(){

		}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public  int invoice_number{
			get;
			set;
		}

		public  Invoice Invoice{
			get;
			set;
		}

		public  Decimal payment_amount{
			get;
			set;
		}

		public  System.DateTime payment_date{
			get;
			set;
		}

		public  int payment_id{
			get;
			set;
		}

	}//end Payments

}//end namespace Indus.Store.Services