///////////////////////////////////////////////////////////
//  DataModel.Ref_Product_Types.cs
//  Implementation of the Class Ref_Product_Types
//  Generated by Enterprise Architect
//  Created on:      05-Oct-2019 12:48:11
//  Original author: ABHILASH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Indus.Store.Models
{
	public partial class Ref_Product_Type {



		~Ref_Product_Type(){

		}

		public Ref_Product_Type(){

		}

	
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
         public  int product_type_code{
			get;
			set;
		}

		public  string product_type_description{
			get;
			set;
		}

	}//end Ref_Product_Types

}//end namespace Indus.Store.Services