///////////////////////////////////////////////////////////
//  DataModel.Ref_Invoice_Status.cs
//  Implementation of the Class Ref_Invoice_Status
//  Generated by Enterprise Architect
//  Created on:      05-Oct-2019 12:48:11
//  Original author: ABHILASH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Indus.Store.Models
{
	public partial class Ref_Invoice_Status {



		~Ref_Invoice_Status(){

		}

		public Ref_Invoice_Status(){

		}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public  int invoice_status_code{
			get;
			set;
		}

		public  string invoice_status_description{
			get;
			set;
		}



	}//end Ref_Invoice_Status

}//end namespace Indus.Store.Services